#!/usr/bin/env bash
cd "$(dirname $0)/.."
pwd

ERRORS=0

function report {
    WHAT="$1"
    let ERRORS++
    echo "Check failed: $WHAT"
}

function check-whitespace-file {
    FILE="$1"
    COUNT=$(grep -c '\s$' "$FILE")
    if [ "$COUNT" -gt 0 ]
        then
            report "trailing whitespace in $FILE"
    fi
}

# First, try to find the 'fd' command
fdcmd="fd"
if ! command -v "$fdcmd" &> /dev/null; then
    # In Ubuntu systems the fd command is called fdfind.
    # If 'fd' is not found, try 'fdfind'
    fdcmd="fdfind"
    if ! command -v "$fdcmd" &> /dev/null; then
        echo "Error: Neither 'fd' nor 'fdfind' command found." >&2
        exit 1
    fi
fi

for FILE in $($fdcmd . ./src ./cli ./test -e hs); do
    # echo "Checking: $FILE"
    check-whitespace-file "$FILE"
done

exit "$ERRORS"
